### ISSUE TITLE
The property 'Name' cannot be found on this object.

### ISSUE THREAD

**Issue by mlaraibkhan** [stefanstranger/logicappdocs#1] opened 2023-07-18 08:48 UTC
Hi, 

I have been using this fantastic tool for a while but suddenly I start getting this error. The -LogicAppName is very simple and does not contain any special characters.

<img width="604" alt="image" src="https://github.com/stefanstranger/logicappdocs/assets/24682607/b10e399b-07dc-41d2-8b2a-7186b9351381">

- One thing I realize while using this tool is: the logic app naming convention shouldn't contain hyphens or underscores while passing -LogicAppName parameter in ps1 script, it fails everytime. Or is there any other way to overcome it that I don't know of?

**Comment by stefanstranger** [comment] 2023-07-24 06:24
Hi @mlaraibkhan,

Can you maybe share your logicapp json code, stripped with any sensitive data with me so I can see where it fails?

You could create a secret gist and share this with me via a Twitter DM [@sstranger](https://twitter.com/sstranger) of [LinkedIn](https://www.linkedin.com/in/stefanstranger/)

Thanks

Stefan

**Comment by mlaraibkhan** [comment] 2023-07-24 09:33
I have shared my logic app JSON file gist via Linkedin message.

On the second issue, I will have to retry that so I will have concrete evidence to share. Thanks

**Comment by stefanstranger** [comment] 2023-07-24 14:57
Hi @mlaraibkhan,

At first look this seemed to be caused by some Actions without any Action configured. I made some changes to validate any actions without an action, but will wait for your confirmation about the changes I made.

Keep me posted on the validation.

Regards,
Stefan Stranger

**Comment by mlaraibkhan** [comment] 2023-07-24 15:09
Hey Stefan,

I did validated the results and I'm happy with them. We can close this issue safely. Thank you.

**Comment by stefanstranger** [comment] 2023-07-27 08:26
Fixed with latest release v1.0.2

**Closed by stefanstranger** 2023-07-27 08:26 UTC
