### ISSUE TITLE
Mermaid diagram parse error

### ISSUE THREAD

**Issue by imorrish** [stefanstranger/logicappdocs#4] opened 2023-07-31 22:10 UTC
My logic app results in the following mermaid diagram which has
Parse error on line 3:
`...  subgraph For_each_|_Smart_Guest_Manage
-----------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'GRAPH', 'DIR', 'subgraph', 'SQS', 'end', 'AMP', 'ALPHA', 'COLON', 'TAGEND', 'START_LINK', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'UP', 'DEFAULT', 'NUM', 'COMMA', 'MINUS', 'BRKT', 'DOT', 'PCT', 'TAGSTART', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'PIPE'
`

Diagram output is:
`
```mermaid
graph TB
    Trigger
    subgraph For_each_|_Smart_Guest_Management_|_Items
    direction TB
        Create_item_|_Smart_Guest_Management_Archive_|_Item
        Delete_item_|_Smart_Guest_Management
    end
    Get_items_|_Smart_Guest_Management --> For_each_|_Smart_Guest_Management_|_Items
    For_each_|_Smart_Guest_Management_|_Items --> Create_item_|_Smart_Guest_Management_Archive_|_Item
    Create_item_|_Smart_Guest_Management_Archive_|_Item --> Delete_item_|_Smart_Guest_Management
    Trigger --> Get_items_|_Smart_Guest_Management

```
`

**Comment by stefanstranger** [comment] 2023-08-01 06:36
Hi Ian,

Thanks for using my logicappsdocs solution 🙏and helping me with fixing issues. Your issue is being caused by the pipe character "|" in the names of your Logic App Actions. 

Mermaid cannot handle certain characters. When I removed the pipe character from the Mermaid code it worked as expected.

See here in the [Mermaid live editor](https://mermaid.live/edit#pako:eNqdUkFuAjEM_MoqZ_jAHioVaFEPnOBURYrcjdmNtElWjlMJIf5ek1B6QkB9suOZsezMUXXRompVTzANzW6hQyOxI9f3SLVI-at23yMZhG4wZuuB2KwzJjYbCNCjx8DGfDD6VFnWEXbsYriKnmNJCIzGCe6myit1g_vGqvZHXeGId6gVjMHWZI1c4OkWvpnPX57b6kFwEf7nrk_TyrCHr3P52kK6eyA1Ux7Jg7NikeNZQCsepKVVK6nFPeSRtdLhJFDIHLeH0Kl2D2PCmcqTlVVWDsQ__vo6QfiMUWqmLCVax5E21YbFjb_Et9K58E4_kTfz2g)

The way to resolve this is that I add a search and replace action for all the actions that contain this character. Are you fine with that solution?

Regards,
Stefan

**Comment by imorrish** [comment] 2023-08-01 06:55
Thanks for looking into that. I had found plenty of other examples regarding "special characters" but guess | is too special. I'

**Comment by stefanstranger** [comment] 2023-08-01 08:27
Let me re-open the issue and close it when I've implemented the fix.

**Comment by stefanstranger** [comment] 2023-08-01 12:59
Closed after merging branch that fixed the error.

**Closed** 2023-08-01 12:59 UTC
Labels: bug
